import { Dice } from "../../core/utils/types/dice";

export enum Equipment {
  AcidVial = "Acid (vial)",
  AlchemistsFireFlask = "Alchemist's fire (flask)",
  AlchemistsSupplies = "Alchemist's Supplies",
  AlmsBox = "Alms box",
  Amulet = "Amulet",
  AnimalFeed1Day = "Animal Feed (1 day)",
  AntitoxinVial = "Antitoxin (vial)",
  Arrow = "Arrow",
  Backpack = "Backpack",
  Bagpipes = "Bagpipes",
  BallBearingsBag1000 = "Ball bearings (bag of 1,000)",
  BardingBreastplate = "Barding: Breastplate",
  BardingChainMail = "Barding: Chain mail",
  BardingChainShirt = "Barding: Chain shirt",
  BardingHalfPlate = "Barding: Half plate",
  BardingHide = "Barding: Hide",
  BardingLeather = "Barding: Leather",
  BardingPadded = "Barding: Padded",
  BardingPlate = "Barding: Plate",
  BardingRingMail = "Barding: Ring mail",
  BardingScaleMail = "Barding: Scale mail",
  BardingSplint = "Barding: Splint",
  BardingStuddedLeather = "Barding: Studded Leather",
  Barrel = "Barrel",
  Basket = "Basket",
  Battleaxe = "Battleaxe",
  Bedroll = "Bedroll",
  Bell = "Bell",
  BitAndBridle = "Bit and bridle",
  Blanket = "Blanket",
  BlockAndTackle = "Block and tackle",
  BlockOfIncense = "Block of incense",
  Blowgun = "Blowgun",
  BlowgunNeedle = "Blowgun needle",
  Book = "Book",
  BottleGlass = "Bottle, glass",
  Breastplate = "Breastplate",
  BrewersSupplies = "Brewer's Supplies",
  Bucket = "Bucket",
  BurglarsPack = "Burglar's Pack",
  CalligraphersSupplies = "Calligrapher's Supplies",
  Caltrops = "Caltrops",
  Camel = "Camel",
  Candle = "Candle",
  CarpentersTools = "Carpenter's Tools",
  Carriage = "Carriage",
  Cart = "Cart",
  CartographersTools = "Cartographer's Tools",
  CaseCrossbowBolt = "Case, crossbow bolt",
  CaseMapOrScroll = "Case, map or scroll",
  Censer = "Censer",
  Chain10Feet = "Chain (10 feet)",
  ChainMail = "Chain Mail",
  ChainShirt = "Chain Shirt",
  Chalk1Piece = "Chalk (1 piece)",
  Chariot = "Chariot",
  Chest = "Chest",
  ClimbersKit = "Climber's Kit",
  ClothesCommon = "Clothes, common",
  ClothesCostume = "Clothes, costume",
  ClothesFine = "Clothes, fine",
  ClothesTravelers = "Clothes, traveler's",
  Club = "Club",
  CobblersTools = "Cobbler's Tools",
  ComponentPouch = "Component pouch",
  CooksUtensils = "Cook's utensils",
  CrossbowBolt = "Crossbow bolt",
  CrossbowHand = "Crossbow, hand",
  CrossbowHeavy = "Crossbow, heavy",
  CrossbowLight = "Crossbow, light",
  Crowbar = "Crowbar",
  Crystal = "Crystal",
  Dagger = "Dagger",
  Dart = "Dart",
  DiceSet = "Dice Set",
  DiplomatsPack = "Diplomat's Pack",
  DisguiseKit = "Disguise Kit",
  Donkey = "Donkey",
  Drum = "Drum",
  Dulcimer = "Dulcimer",
  DungeoneersPack = "Dungeoneer's Pack",
  Elephant = "Elephant",
  Emblem = "Emblem",
  EntertainersPack = "Entertainer's Pack",
  ExplorersPack = "Explorer's Pack",
  FishingTackle = "Fishing tackle",
  Flail = "Flail",
  FlaskOrTankard = "Flask or tankard",
  Flute = "Flute",
  ForgeryKit = "Forgery Kit",
  Galley = "Galley",
  Glaive = "Glaive",
  GlassblowersTools = "Glassblower's Tools",
  GrapplingHook = "Grappling hook",
  Greataxe = "Greataxe",
  Greatclub = "Greatclub",
  Greatsword = "Greatsword",
  Halberd = "Halberd",
  HalfPlateArmor = "Half Plate Armor",
  Hammer = "Hammer",
  HammerSledge = "Hammer, sledge",
  Handaxe = "Handaxe",
  HealersKit = "Healer's Kit",
  HerbalismKit = "Herbalism Kit",
  HideArmor = "Hide Armor",
  HolyWaterFlask = "Holy water (flask)",
  Horn = "Horn",
  HorseDraft = "Horse, draft",
  HorseRiding = "Horse, riding",
  Hourglass = "Hourglass",
  HuntingTrap = "Hunting trap",
  Ink1OunceBottle = "Ink (1 ounce bottle)",
  InkPen = "Ink pen",
  Javelin = "Javelin",
  JewelersTools = "Jeweler's Tools",
  JugOrPitcher = "Jug or pitcher",
  Keelboat = "Keelboat",
  Ladder10Foot = "Ladder (10-foot)",
  Lamp = "Lamp",
  Lance = "Lance",
  LanternBullseye = "Lantern, bullseye",
  LanternHooded = "Lantern, hooded",
  LeatherArmor = "Leather Armor",
  LeatherworkersTools = "Leatherworker's Tools",
  LightHammer = "Light hammer",
  Lock = "Lock",
  Longbow = "Longbow",
  Longship = "Longship",
  Longsword = "Longsword",
  Lute = "Lute",
  Lyre = "Lyre",
  Mace = "Mace",
  MagnifyingGlass = "Magnifying glass",
  Manacles = "Manacles",
  MasonsTools = "Mason's Tools",
  Mastiff = "Mastiff",
  Maul = "Maul",
  MessKit = "Mess Kit",
  MirrorSteel = "Mirror, steel",
  Morningstar = "Morningstar",
  Mule = "Mule",
  NavigatorsTools = "Navigator's Tools",
  Net = "Net",
  OilFlask = "Oil (flask)",
  Orb = "Orb",
  PaddedArmor = "Padded Armor",
  PaintersSupplies = "Painter's Supplies",
  PanFlute = "Pan flute",
  PaperOneSheet = "Paper (one sheet)",
}

export type EquipmentCard = weapon | armor

export type armor = {
  name: string,
  equipment_category: string,
  armor_class: number,
  image: File,

}

export type weapon = {
  name: string,
  equipment_category: Object,
  damage: Dice,
  image: File,
}

