export enum Alignment {
  AnyAlignment = "any alignment",
  AnyChaoticAlignment = "any chaotic alignment",
  AnyEvilAlignment = "any evil alignment",
  AnyNonGoodAlignment = "any non-good alignment",
  AnyNonLawfulAlignment = "any non-lawful alignment",
  ChaoticEvil = "chaotic evil",
  ChaoticGood = "chaotic good",
  ChaoticNeutral = "chaotic neutral",
  HalfNeutral = "neutral good (50%) or neutral evil (50%)",
  LawfulEvil = "lawful evil",
  LawfulGood = "lawful good",
  LawfulNeutral = "lawful neutral",
  Neutral = "neutral",
  NeutralEvil = "neutral evil",
  NeutralGood = "neutral good",
  Unaligned = "unaligned",
}
